server:
  address: 127.0.0.1
  port: 8001
spring:
  application:
    name: security-authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/xwl?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: ${server.address}
    database: 5
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则支持
    cache-enabled: false
  mapper-locations: classpath:com.xwl/**/mapper/*Mapper.xml



signKey: xuewenliang